// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:muscle_up/models/storage/custom_exercise.dart';
import 'package:muscle_up/models/storage/exercise_history.dart';
import 'package:muscle_up/models/storage/set_history.dart';
import 'package:muscle_up/models/storage/stored_exercise_template.dart';
import 'package:muscle_up/models/storage/stored_workout_program.dart';
import 'package:muscle_up/models/storage/workout_history.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CustomExerciseAdapter());
    registerAdapter(ExerciseHistoryAdapter());
    registerAdapter(SetHistoryAdapter());
    registerAdapter(StoredExerciseTemplateAdapter());
    registerAdapter(StoredWorkoutProgramAdapter());
    registerAdapter(WorkoutHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CustomExerciseAdapter());
    registerAdapter(ExerciseHistoryAdapter());
    registerAdapter(SetHistoryAdapter());
    registerAdapter(StoredExerciseTemplateAdapter());
    registerAdapter(StoredWorkoutProgramAdapter());
    registerAdapter(WorkoutHistoryAdapter());
  }
}
